apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: bedrock-kb-retrieval-mcp-server
spec:
  components:
    - name: bedrock-kb-retrieval-mcp-server 
      type: appmod-service
      properties:
        image: 051826708451.dkr.ecr.us-west-2.amazonaws.com/modengg/bedrock-kb-retrieval-mcp-server:init
        image_name: bedrock-kb-retrieval-mcp-server
        port: 8080
        targetPort: 8080
        replicas: 1
        serviceAccountName: bedrock-kb-retrieval-sa
        iamPolicyDocument: |
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Action": [
                  "bedrock:ListFoundationModels",
                  "bedrock:GetFoundationModel",
                  "bedrock:InvokeModel"
                ],
                "Resource": "*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "bedrock-agent:ListKnowledgeBases",
                  "bedrock-agent:GetKnowledgeBase",
                  "bedrock-agent:ListDataSources",
                  "bedrock-agent:ListTagsForResource",
                  "bedrock-agent:RetrieveAndGenerate"
                ],
                "Resource": "*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "bedrock-agent-runtime:Retrieve",
                  "bedrock-agent-runtime:RetrieveAndGenerate"
                ],
                "Resource": "*"
              },
              {
                "Effect": "Allow",
                "Action": [
                  "bedrock:InvokeModelWithResponseStream"
                ],
                "Resource": "*"
              }
            ]
          }
      traits: 
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true 
            http:
              /bedrock-kb-retrieval: 8080
        # Add command and args as a command trait
        - type: command
          properties:
            args:
              - "--port"
              - "8080"
        # Add environment variables as an env trait
        - type: env
          properties:
            env:
              AWS_REGION: us-west-2
              BEDROCK_KB_RERANKING_ENABLED: "false"
              KB_INCLUSION_TAG_KEY: MCP-Enabled
              FASTMCP_LOG_LEVEL: INFO
