apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: nova-canvas-mcp-server
spec:
  components:
    - name: nova-canvas-database
      type: external-database-secret
      properties:
        secret_name: nova-canvas-database
    - name: nova-canvas-mcp-server 
      type: appmod-service
      properties:
        image: 051826708451.dkr.ecr.us-west-2.amazonaws.com/mcp/nova-canvas-mcp-server:latest
        image_name: nova-canvas-mcp-server
        port: 8080
        targetPort: 8080
        replicas: 1
      dependsOn:
        - nova-canvas-database
      traits: 
        - type: path-based-ingress
          properties:
            domain: "*.elb.us-west-2.amazonaws.com"
            rewritePath: true 
            http:
              /nova-canvas: 8080
        - type: storage
          properties:
            secret:
              - name: nova-canvas-database
                mountPath: /opt/secret-volume